[package]
name = "bevy_flash"
version = "0.1.0"
edition = "2021"
authors = ["傲娇小霖霖"]

[dependencies]
swf = { path = "../ruffle/swf" }
ruffle_render = { path = "../ruffle/render" }
ruffle_render_wgpu = { path = "../ruffle/render/wgpu" }
ruffle_macros = { path = "../ruffle/core/macros" }

bevy = { version = "0.14", default-features = false, features = [
    "bevy_render",
    "bevy_asset",
    "bevy_sprite",
    "bevy_core_pipeline",
] }

thiserror = "1.0"
anyhow = "1.0"
bitflags = "2.5"
lyon_tessellation = "1.0"
indexmap = "2.2.6"
copyless = "0.1.5"
smallvec = { version = "1.13.2", features = ["union"] }
wgpu = { version = "0.20", default-features = false }
glam = { version = "0.27" }
uuid = "1.10"

[dev-dependencies]
bevy = { version = "0.14" }


[profile.dev]
opt-level = 1
