[package]
name = "bevy_flash"
version = "0.1.0"
edition = "2021"

[dependencies]
swf = { git = "https://github.com/ruffle-rs/ruffle.git", tag = "nightly-2024-08-06" }
ruffle_render = { git = "https://github.com/ruffle-rs/ruffle.git", tag = "nightly-2024-08-06" }
ruffle_render_wgpu = { git = "https://github.com/ruffle-rs/ruffle.git", tag = "nightly-2024-08-06" }
ruffle_macros = { git = "https://github.com/ruffle-rs/ruffle.git", tag = "nightly-2024-08-06" }

bevy = { version = "0.14", default-features = false, features = [
    "bevy_asset",
    "bevy_sprite",
] }

thiserror = "1.0"
anyhow = "1.0"
bitflags = "2.5"
lyon_tessellation = "1.0"
indexmap = "2.2.6"
copyless = "0.1.5"
smallvec = { version = "1.13.2", features = ["union"] }
wgpu = { version = "0.20", default-features = false }
uuid = "1.10"

[dev-dependencies]
bevy = { version = "0.14" }


[profile.dev]
opt-level = 1
