[package]
name = "bevy_flash"
version = "0.1.0"
edition = "2021"

[dependencies]
swf = { path = "../ruffle/swf" }

ruffle_render = { path = "../ruffle/render" }
ruffle_macros = { path = "../ruffle/core/macros" }

bevy = { version = "0.14", default-features = false, features = [
    "bevy_render",
    "bevy_asset",
    "bevy_sprite",
] }

thiserror = "1.0"
anyhow = "1.0"
fnv = "1.0"
bitflags = "2.5"
smallvec = { version = "1.13.2", features = ["union"] }

[dev-dependencies]
bevy = { version = "0.14" }


[profile.dev]
opt-level = 1
